// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5qjIxIGVz2LbcCSlFMf6MUEiihZIB2hU',
    appId: '1:338723179096:web:49503e864a36dab554582d',
    messagingSenderId: '338723179096',
    projectId: 'ecommerceapp-8185f',
    authDomain: 'ecommerceapp-8185f.firebaseapp.com',
    storageBucket: 'ecommerceapp-8185f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZGGYOgzovRMagEQ4-sU_dbXUd-u1if8Q',
    appId: '1:338723179096:android:aca76609b4fbb81854582d',
    messagingSenderId: '338723179096',
    projectId: 'ecommerceapp-8185f',
    storageBucket: 'ecommerceapp-8185f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiaajGhZ2uM02LGf1hXSWBNWLgxikkvng',
    appId: '1:338723179096:ios:5a1eb7b16c71d47a54582d',
    messagingSenderId: '338723179096',
    projectId: 'ecommerceapp-8185f',
    storageBucket: 'ecommerceapp-8185f.firebasestorage.app',
    androidClientId: '338723179096-m7jtpo5m6fm1uh4s5f9ipj85e8aeljt7.apps.googleusercontent.com',
    iosClientId: '338723179096-r112ge6k6gopbrf457o7hr1s3oea0qq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5qjIxIGVz2LbcCSlFMf6MUEiihZIB2hU',
    appId: '1:338723179096:web:313f29021c37817d54582d',
    messagingSenderId: '338723179096',
    projectId: 'ecommerceapp-8185f',
    authDomain: 'ecommerceapp-8185f.firebaseapp.com',
    storageBucket: 'ecommerceapp-8185f.firebasestorage.app',
  );

}